### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mgrachev**
> You can define a schematic for generating objects by defining Fabricators as spec/fabricators/**/*fabricator.rb.

Source: https://github.com/paulelliott/fabrication-site/blob/master/source/index.markdown

### CODE REVIEW

**Comment by mgrachev** [comment]
@jodosha What do you think about it?

**Comment by jodosha** [comment]
@mgrachev Thank you for this PR.

---

I agree with the name of the file but not with the path.

In new Hanami projects, we generate a `spec_helper.rb` that automatically requires all the files under `spec/support`. See https://github.com/hanami/hanami/blob/master/lib/hanami/generators/application/container/spec_helper.rb.rspec.tt

So, if you put your fabricators under that directory (eg `spec/support/fabricators`), you don't need to require them manually.

**Review by jodosha — CHANGES_REQUESTED** [review]
Please leave under `spec/support`

**Comment by mgrachev** [comment]
@jodosha Done.

**Review by jodosha — APPROVED** [review]
LGTM 👍  Thank you!

**Pull request merged**
